### PR TITLE
Fix/close x

### LINKED ISSUE #2278: Exit on X button instead of minimizing to tray
## Objective
Implement the following behavior for the the x button:
* [enabled minimise to tray] closes the window, but the app is still running in the background and is accessible from systray;
* [disabled minimise to tray] closes the window and quits the app (no background running).

## Testing Notes
Could be linked to the "Show icon in menu bar / system tray". However this setting is non-existent on Windows. So the behaviour on Windows needs to be checked in particular or there needs to be a different configuration option.

## Tips
Implementation most likely to be placed in app/src/browser/mailspring-window.ts

## References
https://community.getmailspring.com/t/exit-on-x-button-with-no-minimize-to-tray/207

### PR DESCRIPTION
**Pull request by Phylu**
Closes #2278.

### CODE REVIEW

File: app/src/browser/mailspring-window.ts [hunk 1]
```diff
@@ -217,22 +217,28 @@ export default class MailspringWindow extends EventEmitter {
...
-          this.browserWindow.hide();
-        }
-
-        // HOWEVER! If the neverClose window is the last window open, and
-        // it looks like there's no windows actually quit the application
-        // on Linux & Windows.
-        if (!this.isSpec) {
-          global.application.windowManager.quitWinLinuxIfNoWindows();
+          // Tray indicator is switched off, therefore quitting the application.
+          app.quit();
```
Comment (bengotow) [inline app/src/browser/mailspring-window.ts:241]: Hey @Phylu! I think this all looks great but I'm not sure offhand if this should be `quit()` or `quitWinLinuxIfNoWindows()`. Technically, this means that if you have the system tray turned off but two Mailspring windows open (the main window and a composer), and close the main window the app will quit. I think that's desirable but let's give it a spin and see!

**Review by bengotow — APPROVED** [review]
Looks great to me! I left one inline comment but I think we ship it and see how it feels, this is definitely an improvement!
